name: Report

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: dauletbaev/parcel-tracker@v1.1
        id: reporter
        with:
          data: ${{ secrets.DATA }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram_id: ${{ secrets.TELEGRAM_ID }}
          last_x_items: '2'
      - run: echo ${{ steps.reporter.outputs.done }}
